### ISSUE TITLE
Make use of smart pointers

### ISSUE THREAD

**Issue by jzobel** [dixx/Die_Chroniken_eines_namenlosen_Spiels#101]
Especially for
- ~~Logger~~ (already a reference)
- Configuration
- Pointerlists

within the engine, a `std::shared_ptr` would be better.
Good read: https://docs.microsoft.com/en-us/cpp/cpp/smart-pointers-modern-cpp?view=vs-2017

**Comment by dixx** [comment]
no `new` in the code atm.
