### ISSUE TITLE
Refactor Game to work with the new Game Engine

### ISSUE THREAD

**Issue by dixx** [dixx/Die_Chroniken_eines_namenlosen_Spiels#71]
To use the new engine and game code as early as possible, we need a second game executable. We can clean up as soon as the two execs behave equal in terms of features.

First feature set:
- [x] new exec loads config values
- [x] new exec is able to run a game loop

This will become v0.5.0

**Comment by dixx** [comment]
have a look at http://gameprogrammingpatterns.com/game-loop.html

**Comment by jzobel** [comment]
use `explicit` keyword for constructors with only one argument.
